"""Regenerate the committed evidence artifact from the suite (WI-5).

    python scripts/emit_evidence.py            # writes EVIDENCE.md, SENSITIVITY.md, REPRODUCE.md
    python scripts/emit_evidence.py --check    # regenerate to a temp dir and diff against the
                                               # committed files; exit 1 on any difference

Every number in the paper must be traceable to a line in these files at a tagged commit.
The files are written deterministically (no timestamps, no git hashes, fixed rounding),
so re-running the script on any machine reproduces them byte-for-byte. Never edit the
generated files by hand.
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ccrlib import scenario, suite  # noqa: E402

POLICY_ORDER = ["random", "card_only", "signature_only", "optimistic_fallback",
                "receipt_only", "ccr", "ccr_r"]
GENERATED = "<!-- GENERATED by scripts/emit_evidence.py — do not edit by hand. -->"


def _f(x, nd=3) -> str:
    return f"{x:.{nd}f}"


def _ci(c: dict) -> str:
    return f"{_f(c['pt'])} [{_f(c['lo'])}, {_f(c['hi'])}]"


def _table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _preamble(seeds: int, tasks: int) -> str:
    p = suite.headline_params()
    return "\n".join([
        f"Setup: `{seeds}` seeds × `{tasks}` tasks = **{seeds * tasks} runs per cell**; "
        f"headline cell V={p.value:g}, λ_R={p.lambda_r:g}, κ={p.canary_cost:g}, "
        f"ρ={p.receipt_cost:g}, B={p.budget:g}, cov={p.attest_coverage:g}, d_H={p.malice_doubt:g}, "
        f"`claim_gap=1.0`, indistinguishable canary, `attest_availability=1.0`.",
        "",
        f"Headline adversary: the **best-response `{suite.HEADLINE_ADVERSARY}` exfiltrator** "
        f"(model-lock A2); `{suite.NAIVE_ADVERSARY}` is the labelled naive contrast. "
        f"CIs are 95% task-clustered bootstrap (n={suite.N_RESAMPLES} resamples, deterministic).",
        "",
        "Every number here is **measured** from a committed run of this artifact. "
        "Reproduce with `python scripts/emit_evidence.py --check` (see `REPRODUCE.md`).",
    ])


# --- EVIDENCE.md -------------------------------------------------------------------

def emit_evidence(seeds: list[int], tasks: list[dict]) -> str:
    n_s, n_t = len(seeds), len(tasks)
    out = [GENERATED, "", "# EVIDENCE — CCR-Receipts headline results", "", _preamble(n_s, n_t), ""]

    # RQ1
    by, cis = suite.rq1(seeds, tasks, ci=True)
    out += ["## RQ1 — Coverage (all policies, headline cell)", ""]
    rows = []
    for pol in POLICY_ORDER:
        r = by.get(pol)
        if not r:
            continue
        rows.append([f"`{pol}`", _f(r["success_rate"]), _f(r["incident_rate"]),
                     _f(r["exfil_incident_rate"]), _f(r["attested_incident_rate"]),
                     _f(r["defection_rate"]), _f(r["mean_net_utility"], 2),
                     _f(r["mean_canaries"], 2), _f(r["mean_receipts"], 2)])
    out.append(_table(["policy", "success", "incident", "exfil_inc", "attested_inc", "defect",
                       "net_util", "canaries", "receipts"], rows))
    out += ["", "95% CIs:", ""]
    out.append(_table(["quantity", "point [lo, hi]"],
                      [[f"`{k}`", _ci(c)] for k, c in cis.items()]))
    out += ["", "`reduction.incident` = paired (task, seed) CCR − CCR-R incident; "
            "`diff.net_utility` = paired CCR-R − CCR net utility.", ""]

    # RQ1 naive contrast
    by_f, _ = suite.rq1(seeds, tasks, adversary=suite.NAIVE_ADVERSARY)
    out += [f"### RQ1 contrast — naive `{suite.NAIVE_ADVERSARY}` adversary (same cell)", ""]
    out.append(_table(["policy", "success", "incident", "exfil_inc", "net_util"],
                      [[f"`{pol}`", _f(by_f[pol]["success_rate"]), _f(by_f[pol]["incident_rate"]),
                        _f(by_f[pol]["exfil_incident_rate"]), _f(by_f[pol]["mean_net_utility"], 2)]
                       for pol in ("ccr", "ccr_r")]))
    out.append("")

    # RQ2
    p = suite.headline_params()
    out += ["## RQ2 — Attestation frontier (sweep ρ)", "",
            f"Receipt-VoI gate at the malice-doubt floor: λ_R·cov·d_H − ρ > 0 ⇒ "
            f"ρ < {p.lambda_r * p.attest_coverage * p.malice_doubt:.2f}.", ""]
    out.append(_table(["ρ", "gate", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "net_gain", "ccrR_receipts"],
                      [[_f(r["rho"], 2), "yes" if r["gate"] else "no", _f(r["ccr_inc"]), _f(r["ccrR_inc"]),
                        _f(r["ccr_net"], 2), _f(r["ccrR_net"], 2), f"{r['net_gain']:+.2f}",
                        _f(r["ccrR_receipts"], 2)]
                       for r in suite.rq2_rho(seeds, tasks)]))
    out.append("")

    # RQ3
    out += ["## RQ3 — Partial adoption (sweep `attest_availability`, headline adversary)", ""]
    out.append(_table(["avail", "ccr_inc", "ccrR_inc", "ccrR_exfil", "ccr_net", "ccrR_net", "ccrR_receipts"],
                      [[_f(r["avail"], 2), _f(r["ccr_inc"]), _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]),
                        _f(r["ccr_net"], 2), _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2)]
                       for r in suite.rq3_adoption(seeds, tasks, suite.HEADLINE_ADVERSARY)]))
    out += ["", "ρ is charged per attestation *request*, whether or not a quote comes back "
            "(symmetric with κ for the canary). The break-even adoption a*(ρ) is in "
            "`SENSITIVITY.md`.", ""]

    # RQ4
    out += ["## RQ4 — Adversary best response (`forge` / `replay` / `absent`, CCR-R)", "",
            f"`{suite.NAIVE_ADVERSARY}` ⇒ self-signed quote, verifies invalid (+{p.risk_forged:.2f}); "
            f"`{suite.REPLAY_ADVERSARY}` ⇒ genuine stale quote (wrong nonce), verifies invalid "
            f"(+{p.risk_forged:.2f}; WI-4, `tests/test_attestation.py`); "
            f"`{suite.HEADLINE_ADVERSARY}` ⇒ no quote (+{p.risk_unattested:.2f}). "
            "`absent` is the exfiltrator's best response.", ""]
    out.append(_table(["avail", "adversary", "ccrR_inc", "ccrR_exfil", "ccrR_net", "ccr_inc (ref)", "ccr_net (ref)"],
                      [[_f(r["avail"], 2), f"`{r['adversary']}`", _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]),
                        _f(r["ccrR_net"], 2), _f(r["ccr_inc"]), _f(r["ccr_net"], 2)]
                       for r in suite.rq4_best_response(seeds, tasks)]))
    out.append("")

    # RQ-COV
    out += [f"## RQ-COV — `attested_yet_abusing` (the cov<1 boundary, WI-2; k={suite.COV_K})", "",
            "Headline pool plus one `attested_yet_abusing` agent per skill: **identical to "
            "`correct` on every observable** (honest declaration 0.90, same description, same "
            "latency profile, runs the audited image ⇒ genuine **valid** quote); the only "
            "difference is the hidden semantic-misuse side effect. `attested_inc` counts "
            f"incidents where the router itself scored the chosen agent as `valid`. Shortlist "
            f"k={suite.COV_K} (full pool) so the benign attestable agents and the abuser compete "
            "head-to-head — k=4 is confounded by top-k crowding (see `SENSITIVITY.md`). "
            f"Net utility at k={suite.COV_K} is k-confounded (k receipts × ρ) and is not a result.", ""]
    byc, shares = suite.rq_cov(seeds, tasks)
    out.append(_table(["policy", "incident", "exfil_inc", "attested_inc", "net_util", "receipts"],
                      [[f"`{pol}`", _f(byc[pol]["incident_rate"]), _f(byc[pol]["exfil_incident_rate"]),
                        _f(byc[pol]["attested_incident_rate"]), _f(byc[pol]["mean_net_utility"], 2),
                        _f(byc[pol]["mean_receipts"], 2)]
                       for pol in ("ccr", "receipt_only", "ccr_r")]))
    out += ["", "Chosen-persona shares (which agent each policy routed to):", ""]
    personas = sorted({k for pol in shares for k in shares[pol]})
    out.append(_table(["policy"] + [f"`{k}`" for k in personas],
                      [[f"`{pol}`"] + [_f(shares[pol].get(k, 0.0)) for k in personas]
                       for pol in ("ccr", "receipt_only", "ccr_r")]))
    out.append("")

    # RQ5
    out += ["## RQ5 — `claim_gap` sweep (CCR vs CCR-R, headline adversary)", "",
            "advantage = CCR incident − CCR-R incident (paired 95% CI).", ""]
    out.append(_table(["claim_gap", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "advantage", "advantage 95% CI"],
                      [[_f(r["claim_gap"], 2), _f(r["ccr_inc"]), _f(r["ccrR_inc"]), _f(r["ccr_net"], 2),
                        _f(r["ccrR_net"], 2), f"{r['advantage']:+.3f}",
                        f"[{_f(r['advantage_ci']['lo'])}, {_f(r['advantage_ci']['hi'])}]"]
                       for r in suite.rq5_claimgap(seeds, tasks, ci=True)]))
    out.append("")
    return "\n".join(out)


# --- SENSITIVITY.md ---------------------------------------------------------------

def emit_sensitivity(seeds: list[int], tasks: list[dict]) -> str:
    n_s, n_t = len(seeds), len(tasks)
    out = [GENERATED, "", "# SENSITIVITY — parameter sweeps", "", _preamble(n_s, n_t), "",
           "Each sweep varies ONE parameter from the headline cell (the others fixed).", ""]

    # RQ-COV family: cov belief, shortlist size k, abuser share, declared cap (WI-2)
    def _shares(d: dict) -> str:
        return ", ".join(f"{k} {_f(v)}" for k, v in d.items())

    out += [f"## `cov` sweep with the `attested_yet_abusing` persona present (CCR-R, k={suite.COV_K})", "",
            "`cov` is the router's *belief* about the runtime-integrity fraction of risk a valid "
            "quote removes. If `attested_inc` stays > 0 at every `cov` — including 1.0 — the "
            "semantic residual is structural (the router cannot see it), not a parameter.", ""]
    out.append(_table(["cov", "gate", "ccrR_inc", "ccrR_exfil", "ccrR_attested_inc", "ccrR_net", "receipts", "ccr_inc (ref)"],
                      [[_f(r["cov"], 2), "yes" if r["gate"] else "no", _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]),
                        _f(r["ccrR_attested_inc"]), _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2), _f(r["ccr_inc"])]
                       for r in suite.sens_cov(seeds, tasks)]))
    out.append("")

    out += ["## Shortlist size `k` sweep for the RQ-COV pool (CCR-R) — the crowding confound", "",
            "At k=4 the four ceiling-declarers (`degraded`, `canary_aware`, exfiltrator, and — in the "
            "over-claim variant — the abuser) fill the shortlist and no `correct` agent is ever probed "
            "or attested; the k=4 row is therefore a crowding artefact, not the WI-2 result.", ""]
    out.append(_table(["k", "ccrR_inc", "ccrR_exfil", "ccrR_attested_inc", "ccrR_net", "receipts", "ccrR chosen shares"],
                      [[str(r["k"]), _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]), _f(r["ccrR_attested_inc"]),
                        _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2), _shares(r["ccrR_shares"])]
                       for r in suite.sens_cov_k(seeds, tasks)]))
    out.append("")

    out += [f"## Abuser-share sweep (`n_attest_abuser` ∈ {{1, 2}} vs 2 `correct` per skill; CCR-R, k={suite.COV_K})", ""]
    out.append(_table(["abusers", "ccrR_inc", "ccrR_exfil", "ccrR_attested_inc", "ccrR_net", "receipts", "ccrR chosen shares"],
                      [[str(r["n_abuser"]), _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]), _f(r["ccrR_attested_inc"]),
                        _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2), _shares(r["ccrR_shares"])]
                       for r in suite.sens_cov_abusers(seeds, tasks)]))
    out.append("")

    out += [f"## Task-sample convergence of the RQ-COV residual (CCR-R, k={suite.COV_K}, {n_s} seeds)", "",
            "The tie among observably identical agents (honest-card abuser vs the two `correct` agents) is "
            "broken by a per-task latency jitter, so the residual is a task-sample statistic. "
            "`share` = abuser's share of runs in which the attested tie group (not `degraded`) was routed to; "
            "`expected` = abusers / (abusers + 2). This table is why the artifact uses "
            f"{n_t} tasks: at 96 tasks the residual is within ~0.03 of its 240-task value.", ""]
    out.append(_table(["tasks", "abusers", "ccrR_attested_inc", "share", "expected", "ccrR chosen shares"],
                      [[str(r["n_tasks"]), str(r["n_abuser"]), _f(r["ccrR_attested_inc"]),
                        _f(r["abuser_share_of_tie_group"]), _f(r["expected_share"]), _shares(r["ccrR_shares"])]
                       for r in suite.sens_cov_convergence(seeds)]))
    out.append("")

    out += [f"## Abuser declared capability — lower vs upper bound (CCR-R, k={suite.COV_K})", "",
            "`honest (0.90)` is the WI-2 headline persona (identical to `correct` on every observable). "
            "`over-claim (CEILING)` is the **upper bound: a card over-claimer with a valid quote** — it "
            "wins the card race, so attestation cannot demote it; reported as a bound, not as the WI-2 result.", ""]
    out.append(_table(["abuser declares", "ccrR_inc", "ccrR_exfil", "ccrR_attested_inc", "ccrR_net", "receipts", "ccrR chosen shares"],
                      [[r["declared"], _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]), _f(r["ccrR_attested_inc"]),
                        _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2), _shares(r["ccrR_shares"])]
                       for r in suite.sens_cov_declared(seeds, tasks)]))
    out.append("")

    # adoption x rho grid
    out += ["## Adoption × ρ grid — break-even adoption a*(ρ) (C3, headline adversary)", "",
            "a*(ρ) = smallest `attest_availability` at which CCR-R's net utility ≥ CCR's "
            "(first grid point where `ccrR_net ≥ ccr_net`, linearly interpolated from the "
            "previous grid point when the crossing falls between two points). Incident "
            "reaches CCR parity at avail=0 regardless of ρ; net utility does not, because "
            "ρ is paid per request.", ""]
    for entry in suite.sens_adoption_rho(seeds, tasks):
        a = entry["a_star"]
        out += [f"### ρ = {entry['rho']:.2f} — a* = {('never' if a is None else _f(a, 3))}", ""]
        out.append(_table(["avail", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "net_gain", "ccrR_receipts"],
                          [[_f(r["avail"], 2), _f(r["ccr_inc"]), _f(r["ccrR_inc"]), _f(r["ccr_net"], 2),
                            _f(r["ccrR_net"], 2), f"{r['ccrR_net'] - r['ccr_net']:+.2f}",
                            _f(r["ccrR_receipts"], 2)]
                           for r in entry["rows"]]))
        out.append("")
    out += ["Summary:", ""]
    out.append(_table(["ρ", "a*(ρ)"],
                      [[_f(e["rho"], 2), "never" if e["a_star"] is None else _f(e["a_star"], 3)]
                       for e in suite.sens_adoption_rho(seeds, tasks)]))
    out.append("")

    # rho (same as RQ2, listed here for completeness of the sensitivity file)
    out += ["## ρ sweep (attestation frontier; same cells as EVIDENCE RQ2)", ""]
    out.append(_table(["ρ", "gate", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "net_gain"],
                      [[_f(r["rho"], 2), "yes" if r["gate"] else "no", _f(r["ccr_inc"]), _f(r["ccrR_inc"]),
                        _f(r["ccr_net"], 2), _f(r["ccrR_net"], 2), f"{r['net_gain']:+.2f}"]
                       for r in suite.rq2_rho(seeds, tasks)]))
    out.append("")

    # lambda_r
    out += ["## λ_R sweep (price of an incident)", ""]
    out.append(_table(["λ_R", "gate", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "ccrR_receipts"],
                      [[_f(r["lambda_r"], 1), "yes" if r["gate"] else "no", _f(r["ccr_inc"]), _f(r["ccrR_inc"]),
                        _f(r["ccr_net"], 2), _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2)]
                       for r in suite.sens_lambda_r(seeds, tasks)]))
    out.append("")

    # d_H
    out += ["## d_H sweep (malice-doubt floor of the receipt gate)", ""]
    out.append(_table(["d_H", "gate", "ccr_inc", "ccrR_inc", "ccr_net", "ccrR_net", "ccrR_receipts"],
                      [[_f(r["d_H"], 2), "yes" if r["gate"] else "no", _f(r["ccr_inc"]), _f(r["ccrR_inc"]),
                        _f(r["ccr_net"], 2), _f(r["ccrR_net"], 2), _f(r["ccrR_receipts"], 2)]
                       for r in suite.sens_malice_doubt(seeds, tasks)]))
    out.append("")

    # attest_availability, both adversaries
    out += ["## `attest_availability` sweep, all three adversary variants (CCR-R)", ""]
    rows = []
    for adv in (suite.HEADLINE_ADVERSARY, suite.NAIVE_ADVERSARY, suite.REPLAY_ADVERSARY):
        for r in suite.rq3_adoption(seeds, tasks, adv):
            rows.append([f"`{adv}`", _f(r["avail"], 2), _f(r["ccrR_inc"]), _f(r["ccrR_exfil"]),
                         _f(r["ccrR_net"], 2), _f(r["ccr_inc"]), _f(r["ccr_net"], 2)])
    out.append(_table(["adversary", "avail", "ccrR_inc", "ccrR_exfil", "ccrR_net", "ccr_inc (ref)", "ccr_net (ref)"], rows))
    out.append("")

    # claim_gap (same as RQ5)
    out += ["## `claim_gap` sweep (same cells as EVIDENCE RQ5)", ""]
    out.append(_table(["claim_gap", "ccr_inc", "ccrR_inc", "advantage", "advantage 95% CI"],
                      [[_f(r["claim_gap"], 2), _f(r["ccr_inc"]), _f(r["ccrR_inc"]), f"{r['advantage']:+.3f}",
                        f"[{_f(r['advantage_ci']['lo'])}, {_f(r['advantage_ci']['hi'])}]"]
                       for r in suite.rq5_claimgap(seeds, tasks, ci=True)]))
    out.append("")
    return "\n".join(out)


# --- REPRODUCE.md -----------------------------------------------------------------

def emit_reproduce(n_seeds: int, n_tasks: int) -> str:
    return "\n".join([
        GENERATED, "",
        "# REPRODUCE", "",
        "Python 3.10+ standard library only — nothing to install. Deterministic: no `random`, "
        "all draws come from `ccrlib/domain.det_unit` hashing, so every machine produces the "
        "same bytes.", "",
        "```bash",
        f"python scripts/emit_evidence.py            # rewrite EVIDENCE.md, SENSITIVITY.md, REPRODUCE.md "
        f"({n_seeds} seeds x {n_tasks} tasks)",
        "python scripts/emit_evidence.py --check    # regenerate to a temp dir and diff against the committed files",
        "python scripts/run.py --ci                 # console view of the same cells (RQ1..RQ5, RQ-COV)",
        "python -m unittest discover tests          # attestation verifier self-test (valid / forge / replay)",
        "```", "",
        "`--check` exits non-zero if any generated file differs from the committed one — run it "
        "before citing a number. To cite a number in the paper, cite the git tag of the commit "
        "that contains these files (e.g. `aamas27-evidence-v1`).", "",
        "Cell definitions live in `ccrlib/suite.py`; both scripts call the same functions.", "",
    ])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, default=8)
    ap.add_argument("--tasks", type=int, default=96)
    ap.add_argument("--check", action="store_true",
                    help="regenerate into a temp dir and diff against the committed files")
    args = ap.parse_args()
    seeds = list(range(args.seeds))
    tasks = scenario.build_tasks(args.tasks)

    files = {
        "EVIDENCE.md": emit_evidence(seeds, tasks),
        "SENSITIVITY.md": emit_sensitivity(seeds, tasks),
        "REPRODUCE.md": emit_reproduce(args.seeds, args.tasks),
    }
    if args.check:
        bad = []
        for name, content in files.items():
            path = os.path.join(ROOT, name)
            committed = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if committed != content:
                bad.append(name)
        if bad:
            tmp = tempfile.mkdtemp(prefix="ccr-evidence-")
            for name in bad:
                with open(os.path.join(tmp, name), "w", encoding="utf-8") as fh:
                    fh.write(files[name])
            print(f"MISMATCH: {', '.join(bad)} differ from the committed files "
                  f"(regenerated copies in {tmp})")
            sys.exit(1)
        print("OK: EVIDENCE.md, SENSITIVITY.md, REPRODUCE.md match the committed files.")
        return
    for name, content in files.items():
        with open(os.path.join(ROOT, name), "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {name}")


if __name__ == "__main__":
    main()
